import { useEffect } from "react";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';



import WalletContextProvider from "./components/walletContextProvider";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* BLACK GRADIENT BACKGROUND */}
      {/* <body className="relative bg-gradient-to-r from-slate-800 via-zinc-5-800 to-stone-800 p-8 rounded-lg shadow-lg"> */}
      <body>
        {/** Wallet Context */}
        <WalletContextProvider>
          <Header/>
        {/** Toast Container for notifications */}
        <ToastContainer 
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        {children}
        </WalletContextProvider>
        <Footer/>
      </body>
    </html>
  );
}
